apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python-deployment
  labels:
    app: hello-python-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-python-deployment
  template:
    metadata:
      labels:
        app: hello-python-deployment
    spec:
      containers:
      - name: hello-python-container
        image: danielrcode/applications:latest
        ports:
        - containerPort: 5000