apiVersion: batch/v1
kind: Job
metadata:
  name: post-sync-job
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: github-trigger
        image: curlimages/curl:latest
        command:
          - sh
          - -c
          - |
            set -o pipefail

            client_id=$(cat /mnt/secrets/github-app-secret/APP_ID)
            pem=$(cat /mnt/secrets/github-app-secret/private-key.pem)
            installation_id=$(cat /mnt/secrets/github-app-secret/INSTALLATION_ID)

            now=$(date +%s)
            iat=$((${now} - 60)) # Issues 60 seconds in the past
            exp=$((${now} + 600)) # Expires 10 minutes in the future

            b64enc() { openssl base64 | tr -d '=' | tr '/+' '_-' | tr -d '\n'; }

            header_json='{
                "typ":"JWT",
                "alg":"RS256"
            }'
            # Header encode
            header=$( echo -n "${header_json}" | b64enc )

            payload_json='{
                "iat":'"${iat}"',
                "exp":'"${exp}"',
                "iss":'"${client_id}"'
            }'
            # Payload encode
            payload=$( echo -n "${payload_json}" | b64enc )

            # Signature
            header_payload="${header}"."${payload}"
            signature=$(
                openssl dgst -sha256 -sign <(echo -n "${pem}") \
                <(echo -n "${header_payload}") | b64enc
            )

            # Create JWT
            JWT="${header_payload}"."${signature}"
            printf '%s\n' "JWT: $JWT"

            # Exchange the JWT for an installation token
            INSTALLATION_TOKEN=$(curl -X POST \
                -H "Authorization: Bearer $JWT" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/app/installations/$installation_id/access_tokens | jq -r .token)

            echo $INSTALLATION_TOKEN

            curl -X POST \
              -H "Accept: application/vnd.github.everest-preview+json" \
              -H "Authorization: Bearer $INSTALLATION_TOKEN" \
              https://api.github.com/repos/your-username/your-repo/dispatches \
              -d '{"event_type":"argo_event"}'

        volumeMounts:
        - name: github-app-secret
          mountPath: /mnt/secrets/github-app-secret
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: github-app-secret
        secret:
          secretName: github-app-secret
